apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-json-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-json-server
  template:
    metadata:
      labels:
        app: contact-json-server
    spec:
      containers:
      - name: contact-json-server
        image: vipinkumar71/contact-app:json-server
        ports:
        - containerPort: 5000
        command: ["json-server", "--watch", "db.json", "--host", "0.0.0.0"]
