apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contact-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/vipinkumar71/contact-app
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: contact-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true