apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-app
  template:
    metadata:
      labels:
        app: contact-app
    spec:
      containers:
      - name: contact-app
        image: your-dockerhub-username/contact-app:json-server
        ports:
        - containerPort: 80  # For React app
        - containerPort: 5000 # For JSON server
---
apiVersion: v1
kind: Service
metadata:
  name: contact-app-service
spec:
  type: NodePort
  selector:
    app: contact-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30008
