apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-app
  template:
    metadata:
      labels:
        app: contact-app
    spec:
      containers:
      - name: contact-app
        image: contact-app:latest
        ports:
        - containerPort: 3000
        - containerPort: 5000
        env:
        - name: REACT_APP_JSON_SERVER_URL
          value: "http://localhost:5000"
