apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contact-app
  template:
    metadata:
      labels:
        app: contact-app
    spec:
      containers:
      - name: contact-app
        image: contact-app:v1
        ports:
        - containerPort: 5000  # JSON Server runs on port 5000
