apiVersion: v1
kind: Service
metadata:
  name: contact-app-service
spec:
  type: NodePort
  ports:
    - port: 5000         # The port your service listens on
      targetPort: 5000   # The port your container listens on
      nodePort: 30000    # Choose a port between 30000-32767
  selector:
    app: contact-app
