# apiVersion: v1
# kind: Service
# metadata:
#   name: contact-app-service
# spec:
#   selector:
#     app: contact-app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: contact-app-service
spec:
  type: NodePort
  selector:
    app: contact-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080

